### ISSUE TITLE
Vite 4 support

### ISSUE THREAD

**Issue by Subwaytime** [Subwaytime/vite-aliases#48]
support the upcoming vite 4

**Comment by Subwaytime** [comment]
#46 , #47 - should be covered by these changes

**Comment by agm1984** [comment]
Sorry to direct usage away from this library that I enjoyed, but I was trying to update today to Vite 4 and found this issue, but I was able to sidestep it because my entire project just uses the most simple alias which is 
```
import Thing from '@/components/Thing.vue';
import { useSomeStore } from '@/store/some';
import { formatThing } from '@/utils/numbers.js';
// ... etc
```

So I was able to use Vite 4 by removing `vite-aliases` entirely and using this instead:

``` javascript
// vite.config.js
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import eslint from 'vite-plugin-eslint';
import Components from 'unplugin-vue-components/vite';
import path from 'path';

// https://vitejs.dev/config/
export default defineConfig({
    server: {
        port: 3000,
    },

    plugins: [
        vue(),

        // This raises ESLint errors into the browser
        eslint(),

        // This autoloads all components in the /src/components directory
        Components(),
    ],

    resolve: {
        alias: [{
            find: '@', replacement: path.resolve(__dirname, 'src'),
        }],
    },
});
```

Working with:
```
    "@vitejs/plugin-vue": "^4.0.0",
    "unplugin-vue-components": "^0.22.12",
    "vite": "^4.0.1",
    "vite-plugin-eslint": "^1.8.1",
```

If you are using TypeScript or ESLint import resolver plugin, you may find this original link useful: https://stackoverflow.com/questions/67835072/vue-3-on-vite-js-with-eslint-unable-to-resolve-path-to-module-eslintimport-no

**Comment by Subwaytime** [comment]
@agm1984 this comment has been made before, the library does not support vite 4 atm so its clear that there will be issues. Using one alias is fine, but it defeats the purpose of posting it here because this library is made for other purposes mainly deeply structured projects like monorepo or generally for projects that need more in-depth orgranisation.

**Comment by Subwaytime** [comment]
[v.0.9.9](https://github.com/Subwaytime/vite-aliases/releases/tag/v0.9.9) - now supports vite 4 (experimental)

**Comment by Subwaytime** [comment]
[v0.10.0](https://github.com/Subwaytime/vite-aliases/releases/tag/v0.10.0) - ensures vite 4 support.
